<!DOCTYPE html>
<html>
<body>

<h2>CUSTOMER DETAILS</h2>

<form action="/cust/index/save" method="POST">
  ENTER YOUR  NAME :<br>
  <input type="text" name="CUSTOMER_NAME" value="NAME">
  <br>
  PHONE NUMBER   :<br>
  <input type="text" name="PHONE_NUMBER" value="NUMBER">
  <br><br>
  ADDRESS  :<br>
  <input type="text" name="ADDRESS" value="ADDRESS">
  <br><br>
  <input type="submit" value="Submit">
</form>

<p>If you click the "Submit" button, the form-data will be sent to a page called "/action_page.php".</p>

</body>
</html>
